services:
  db:
    image: mysql:latest
    volumes:
      - mysql_data:/var/lib/mysql
      - ./weinhandel.sql:/docker-entrypoint-initdb.d/weinhandel.sql
    restart: always
    environment:
      MYSQL_DATABASE: 'weinhandel'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'docker_password'
      MYSQL_ROOT_PASSWORD: 'docker_password'
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 1s
      retries: 10

  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/code
    ports:
      - "0.0.0.0:8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_HOST: db
      DATABASE_NAME: weinhandel
      DATABASE_USER: user
      DATABASE_PASSWORD: docker_password
      DATABASE_PORT: 3306
volumes:
  mysql_data: