# Generated by Django 5.0.6 on 2024-05-14 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_reservedorder_purchase_delete_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.AlterField(
            model_name='reservedorder',
            name='state',
            field=models.IntegerField(blank=True, choices=[(0, 'Pending'), (1, 'Whishlist'), (2, 'Purchased')], default=0, null=True),
        ),
        migrations.CreateModel(
            name='ProductVintage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vintage', models.IntegerField()),
                ('vintage_description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('stock', models.PositiveIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
        ),
        migrations.AlterField(
            model_name='reservedorder',
            name='product',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.productvintage'),
        ),
    ]
